### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by solonovamax** [Sk1erLLC/AutoGG#19]
Cannot build project because the nexus repository is private and requires a username and password.

And since this repo is currently under the GPLv3, that is in violation of the license.
For two reasons, actually.
- [If you're distributing binaries, you must be able to compile the GPL program](https://opensource.stackexchange.com/a/2690)
- [You cannot link a GPL program with a non-free library](https://stackoverflow.com/a/1854944)

**Comment by Sk1er** [comment]
For the time being one of the libraries is not yet public. We could have private the repo outright but decided to keep it up for reference in the interim.

**Comment by solonovamax** [comment]
How long will it take for Essentials/Modcore to be released? Because I wanted to just make a few (personal) modifications to it, then recompile.

**Comment by Sk1er** [comment]
I can't comment on our timeline but you can back a few commits to before we made these changes

**Comment by solonovamax** [comment]
Probably just gonna hack together my own version of autogg in kotlin with _most_ of the same features.

**Comment by asbyth** [comment]
resolved in https://github.com/Sk1erLLC/AutoGG/commit/3bd1c1a627e5d12ff5cc19fd63b6cd48c91c3bef

**Comment by solonovamax** [comment]
pogg
