### ISSUE TITLE
Pre-compile all regex patterns rather than on first client chat event

### ISSUE THREAD

**Issue by solonovamax** [Sk1erLLC/AutoGG#23]
All of the autogg patterns are compiled at runtime, on the first `ClientChatReceivedEvent` event, rather than being compiled by the `RetrieveTriggersTask` when they're fetched.
It would be much nicer to have them compiled when they're fetched, for performance reasons.

See: [`AutoGGHandler#66`](https://github.com/Sk1erLLC/AutoGG/blob/eff47abcc41e6197b193736c625c4baa5b83481d/src/main/java/club/sk1er/mods/autogg/handlers/gg/AutoGGHandler.java#L66).

**Comment by Sychic** [comment]
In `RetrieveTriggersTask`, all the patterns are compiled 
https://github.com/Sk1erLLC/AutoGG/blob/0a980d32ed4e3839d5f3bb4d6c0eccf693a95178/src/main/java/club/sk1er/mods/autogg/tasks/RetrieveTriggersTask.java#L41-L46

**Comment by solonovamax** [comment]
nvm, I'm just dumb
