### ISSUE TITLE
Does not work with duels update

### ISSUE THREAD

**Issue by TheKodeToad** [Sk1erLLC/AutoGG#24]
The AutoGG regex no longer works with The Bridge (it was recently changed to "Bridge Duel" from "The Bridge Duel"), boxing or parkour. I was able to fix it by manually changing the regex:
` +(((?:UHC|SkyWars|(The )?Bridge|Sumo|Classic|OP|MegaWalls|Bow|NoDebuff|Blitz|Combo|Bow Spleef|Boxing) (?:Duel|Doubles|Teams|Deathmatch|2v2v2v2|3v3v3v3)?)|Hypixel Parkour) ?- \\d+:\\d+$`

This is just an example. It may be better to create a new pattern for "Hypixel Parkour".

I cannot open a pull request as it is remotely hosted.

**Comment by Sychic** [comment]
Done
