### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by BarraR3port** [Sk1erLLC/AutoGG#26]
I just hit `build` in the gradle task list and this error show up

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':1.8.9:applyBinaryPatches'.
> java/util/jar/Pack200

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
21:18:32: Execution finished 'build'.

**Comment by asbyth** [comment]
most likely resolved with https://github.com/Sk1erLLC/AutoGG/commit/ba55bfeed70900c73ebe7c6b788fbcfebd8f4ad8
check it & reopen if the issue persists
